services:
  web:
    build: .
    ports:
      - 90:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 99:3306
volumes:
  db_data: